"""Schémas d'entrée et de sortie de l'API."""

from msm.api.schemas.auth import (
    CsrfOut,
    LoginRequest,
    MeOut,
    PasswordChangeRequest,
    UserCreateRequest,
    UserOut,
    UserUpdateRequest,
)
from msm.api.schemas.console import (
    AuditEntryOut,
    AuditPageOut,
    CommandInspectOut,
    CommandOut,
    CommandRequest,
    LogLineOut,
    LogsOut,
    StopOut,
)
from msm.api.schemas.player import (
    BanRequest,
    GiveRequest,
    KickRequest,
    PlayerActionOut,
    PlayerOut,
    TeleportRequest,
)
from msm.api.schemas.server import (
    DashboardOut,
    DetectionOut,
    DetectRequest,
    JarCandidateOut,
    ServerCreateRequest,
    ServerOut,
    ServerSettingsIn,
    ServerSettingsOut,
    ServerUpdateRequest,
)

__all__ = [
    "AuditEntryOut",
    "AuditPageOut",
    "BanRequest",
    "CommandInspectOut",
    "CommandOut",
    "CommandRequest",
    "CsrfOut",
    "DashboardOut",
    "DetectRequest",
    "DetectionOut",
    "GiveRequest",
    "JarCandidateOut",
    "KickRequest",
    "LogLineOut",
    "LoginRequest",
    "LogsOut",
    "MeOut",
    "PasswordChangeRequest",
    "PlayerActionOut",
    "PlayerOut",
    "ServerCreateRequest",
    "ServerOut",
    "ServerSettingsIn",
    "ServerSettingsOut",
    "ServerUpdateRequest",
    "StopOut",
    "TeleportRequest",
    "UserCreateRequest",
    "UserOut",
    "UserUpdateRequest",
]
