"""schema initial

Revision ID: 3d476356818d
Revises: 
Create Date: 2026-08-10 01:26:27.661743
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '3d476356818d'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_app_settings'))
    )
    op.create_table('servers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('directory', sa.String(length=1024), nullable=False),
    sa.Column('server_type', sa.Enum('VANILLA', 'FORGE', 'NEOFORGE', 'FABRIC', 'QUILT', 'MOHIST', 'PAPER', 'SPIGOT', 'BUKKIT', 'PURPUR', 'CUSTOM', 'UNKNOWN', name='servertype', native_enum=False, length=24), nullable=False),
    sa.Column('minecraft_version', sa.String(length=32), nullable=True),
    sa.Column('launcher_key', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_servers')),
    sa.UniqueConstraint('name', name=op.f('uq_servers_name'))
    )
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_servers_slug'), ['slug'], unique=True)

    op.create_table('skin_cache',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=16), nullable=True),
    sa.Column('texture_url', sa.String(length=512), nullable=True),
    sa.Column('avatar_path', sa.String(length=512), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('not_found', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_skin_cache'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MODERATOR', 'VIEWER', name='role', native_enum=False, length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_username', sa.String(length=64), nullable=False),
    sa.Column('actor_role', sa.String(length=16), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('action', sa.Enum('LOGIN', 'LOGIN_FAILED', 'LOGOUT', 'PASSWORD_CHANGED', 'SERVER_CREATED', 'SERVER_UPDATED', 'SERVER_DELETED', 'SERVER_STARTED', 'SERVER_STOPPED', 'SERVER_RESTARTED', 'SERVER_KILLED', 'COMMAND_SENT', 'PLAYER_OP', 'PLAYER_DEOP', 'PLAYER_KICKED', 'PLAYER_BANNED', 'PLAYER_UNBANNED', 'PLAYER_KILLED', 'PLAYER_GIVE', 'PLAYER_TELEPORTED', 'FILE_UPLOADED', 'FILE_DELETED', 'FILE_ENABLED', 'FILE_DISABLED', 'CONFIG_UPDATED', 'PROPERTIES_UPDATED', 'EULA_ACCEPTED', 'EVENT_RUN', 'USER_CREATED', 'USER_UPDATED', 'USER_DELETED', 'PERMISSIONS_UPDATED', 'SETTINGS_UPDATED', name='auditaction', native_enum=False, length=48), nullable=False),
    sa.Column('result', sa.Enum('SUCCESS', 'DENIED', 'ERROR', name='auditresult', native_enum=False, length=8), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.Column('target_type', sa.String(length=32), nullable=True),
    sa.Column('target_id', sa.String(length=128), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], name=op.f('fk_audit_logs_server_id_servers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index('ix_audit_logs_actor_ts', ['actor_id', 'ts'], unique=False)
        batch_op.create_index('ix_audit_logs_server_ts', ['server_id', 'ts'], unique=False)
        batch_op.create_index('ix_audit_logs_ts_desc', ['ts'], unique=False)

    op.create_table('backups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='backupstatus', native_enum=False, length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_backups_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], name=op.f('fk_backups_server_id_servers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backups'))
    )
    with op.batch_alter_table('backups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backups_server_id'), ['server_id'], unique=False)

    op.create_table('event_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_event_definitions_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], name=op.f('fk_event_definitions_server_id_servers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_definitions'))
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('username', sa.String(length=16), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_sessions', sa.Integer(), nullable=False),
    sa.Column('is_op', sa.Boolean(), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('is_whitelisted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], name=op.f('fk_players_server_id_servers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_players')),
    sa.UniqueConstraint('server_id', 'uuid', name=op.f('uq_players_server_id'))
    )
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_players_server_id'), ['server_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_username'), ['username'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_uuid'), ['uuid'], unique=False)

    op.create_table('server_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('granted', sa.JSON(), nullable=False),
    sa.Column('revoked', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], name=op.f('fk_server_permissions_server_id_servers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_server_permissions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_server_permissions')),
    sa.UniqueConstraint('user_id', 'server_id', name=op.f('uq_server_permissions_user_id'))
    )
    with op.batch_alter_table('server_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_server_permissions_server_id'), ['server_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_server_permissions_user_id'), ['user_id'], unique=False)

    op.create_table('server_runtime_state',
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('OFFLINE', 'STARTING', 'ONLINE', 'STOPPING', 'CRASHED', 'UNKNOWN', name='serverstate', native_enum=False, length=16), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('process_create_time', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_exit_code', sa.Integer(), nullable=True),
    sa.Column('consecutive_crashes', sa.Integer(), nullable=False),
    sa.Column('stop_requested', sa.Boolean(), nullable=False),
    sa.Column('last_error', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], name=op.f('fk_server_runtime_state_server_id_servers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('server_id', name=op.f('pk_server_runtime_state'))
    )
    op.create_table('server_settings',
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('java_path', sa.String(length=1024), nullable=True),
    sa.Column('jar_path', sa.String(length=1024), nullable=True),
    sa.Column('script_path', sa.String(length=1024), nullable=True),
    sa.Column('custom_argv', sa.JSON(), nullable=False),
    sa.Column('jvm_args', sa.JSON(), nullable=False),
    sa.Column('extra_args', sa.JSON(), nullable=False),
    sa.Column('env', sa.JSON(), nullable=False),
    sa.Column('memory_min_mb', sa.Integer(), nullable=True),
    sa.Column('memory_max_mb', sa.Integer(), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('stop_command', sa.String(length=64), nullable=False),
    sa.Column('stop_timeout_s', sa.Float(), nullable=False),
    sa.Column('kill_timeout_s', sa.Float(), nullable=False),
    sa.Column('start_timeout_s', sa.Float(), nullable=False),
    sa.Column('auto_restart', sa.Enum('NEVER', 'ON_CRASH', 'ALWAYS', name='autorestartmode', native_enum=False, length=16), nullable=False),
    sa.Column('restart_delay_s', sa.Float(), nullable=False),
    sa.Column('max_consecutive_crashes', sa.Integer(), nullable=False),
    sa.Column('autostart_on_boot', sa.Boolean(), nullable=False),
    sa.Column('auto_accept_eula', sa.Boolean(), nullable=False),
    sa.Column('log_history_lines', sa.Integer(), nullable=False),
    sa.Column('use_pty', sa.Boolean(), nullable=False),
    sa.Column('rcon_enabled', sa.Boolean(), nullable=False),
    sa.Column('rcon_port', sa.Integer(), nullable=True),
    sa.Column('rcon_password_enc', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], name=op.f('fk_server_settings_server_id_servers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('server_id', name=op.f('pk_server_settings'))
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_sessions'))
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sessions_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('event_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('started_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='eventrunstatus', native_enum=False, length=16), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('total_steps', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('log', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event_definitions.id'], name=op.f('fk_event_runs_event_id_event_definitions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], name=op.f('fk_event_runs_server_id_servers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['started_by'], ['users.id'], name=op.f('fk_event_runs_started_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_runs'))
    )
    with op.batch_alter_table('event_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_runs_server_id'), ['server_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_runs_server_id'))

    op.drop_table('event_runs')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_token_hash'))

    op.drop_table('user_sessions')
    op.drop_table('server_settings')
    op.drop_table('server_runtime_state')
    with op.batch_alter_table('server_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_server_permissions_user_id'))
        batch_op.drop_index(batch_op.f('ix_server_permissions_server_id'))

    op.drop_table('server_permissions')
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_uuid'))
        batch_op.drop_index(batch_op.f('ix_players_username'))
        batch_op.drop_index(batch_op.f('ix_players_server_id'))

    op.drop_table('players')
    op.drop_table('event_definitions')
    with op.batch_alter_table('backups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backups_server_id'))

    op.drop_table('backups')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_logs_ts_desc')
        batch_op.drop_index('ix_audit_logs_server_ts')
        batch_op.drop_index('ix_audit_logs_actor_ts')
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    op.drop_table('skin_cache')
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_servers_slug'))

    op.drop_table('servers')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
